# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/dopinder/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dopinder)

$(call add-radio-file-sha1-checked,radio/bootloader.img,1c399aac0d436e0d21616c89c6929d05f12eeca7)

endif
