# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/dopinder/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dopinder)

$(call add-radio-file-sha1-checked,radio/bootloader.img,83abf8b1ff8f51d53119a68dd30b27255644df84)

endif
